// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDys7WMNluTha7LnKDbZNOzYpUadrhSa-w',
    appId: '1:1001525307280:web:b5d359d79a5116da923515',
    messagingSenderId: '1001525307280',
    projectId: 'mukkadam-d4733',
    authDomain: 'mukkadam-d4733.firebaseapp.com',
    storageBucket: 'mukkadam-d4733.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOKCsvNePFjCTSHyI1DgbMvFA0P1nbCb8',
    appId: '1:1001525307280:android:eb6a5fa5d79a87fb923515',
    messagingSenderId: '1001525307280',
    projectId: 'mukkadam-d4733',
    storageBucket: 'mukkadam-d4733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO2mZXiYCOWIPnn1u1ge16DM4mQJYr1NI',
    appId: '1:1001525307280:ios:b62260e0ee929ef2923515',
    messagingSenderId: '1001525307280',
    projectId: 'mukkadam-d4733',
    storageBucket: 'mukkadam-d4733.firebasestorage.app',
    iosBundleId: 'com.example.mukadamBi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO2mZXiYCOWIPnn1u1ge16DM4mQJYr1NI',
    appId: '1:1001525307280:ios:b62260e0ee929ef2923515',
    messagingSenderId: '1001525307280',
    projectId: 'mukkadam-d4733',
    storageBucket: 'mukkadam-d4733.firebasestorage.app',
    iosBundleId: 'com.example.mukadamBi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDys7WMNluTha7LnKDbZNOzYpUadrhSa-w',
    appId: '1:1001525307280:web:f2ec9412e30fbd36923515',
    messagingSenderId: '1001525307280',
    projectId: 'mukkadam-d4733',
    authDomain: 'mukkadam-d4733.firebaseapp.com',
    storageBucket: 'mukkadam-d4733.firebasestorage.app',
  );
}
